server:
  port: 8081
logging.level:
  com.example: debug
spring:
  data.mongodb.uri: mongodb://kadav8:${MONGO_MLAB_PASSWORD}@ds227939.mlab.com:27939/mongo
  cloud.stream:
    bindings:
      input:
        destination: documents
        group: documents-group
        binder: rabbit1
    binders:
      rabbit1:
        type: rabbit
        environment:
          spring:
            rabbitmq:
              host: sheep.rmq.cloudamqp.com
              username: ${RABBIT_USERNAME}
              password: ${RABBIT_PASSWORD}
              virtual-host: ${RABBIT_USERNAME}