server:
    port: 2222
eureka:
    client:
        enabled: true
        serviceUrl.defaultZone: http://localhost:1111/eureka/
spring:
    cloud.config.server.native.search-locations: classpath:/shared
    security.user.password: 12345
    profiles.active: native